-- -- 코드를 입력하세요
-- SELECT PRODUCT_ID
--       ,PRODUCT_NAME
--       ,SUM(PRICE) AS TOTAL_SALES
--   FROM (
--         SELECT A.PRODUCT_ID
--               ,A.PRODUCT_NAME
--               ,A.PRICE
--           FROM FOOD_PRODUCT A
--           INNER JOIN FOOD_ORDER B
--             ON A.PRODUCT_ID = B.PRODUCT_ID
--          WHERE TO_CHAR(B.PRODUCE_DATE, 'YYYY-MM')  = '2022-05'
--        )
-- GROUP BY PRODUCT_ID
--         ,PRODUCT_NAME
-- ORDER BY PRODUCT_ID



 SELECT A.PRODUCT_ID
      ,A.PRODUCT_NAME
      ,SUM(A.PRICE * B.AMOUNT)  AS TOTAL_SALES
  FROM FOOD_PRODUCT A
  INNER JOIN FOOD_ORDER B
    ON A.PRODUCT_ID = B.PRODUCT_ID
 WHERE TO_CHAR(B.PRODUCE_DATE, 'YYYY-MM')  = '2022-05'
GROUP BY A.PRODUCT_ID
        ,A.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC
        ,A.PRODUCT_ID;

