-- 코드를 입력하세요
SELECT
    a.WRITER_ID,
    b.NICKNAME,
    SUM(PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_BOARD a,
    USED_GOODS_USER b
WHERE 
    a.WRITER_ID = b.USER_ID
AND
    a.STATUS = 'DONE'
GROUP BY  
    a.WRITER_ID,
    b.NICKNAME
HAVING
    SUM(PRICE) >= 700000
ORDER BY
    TOTAL_SALES;