-- 코드를 입력하세요
SELECT
    DATETIME
    , COUNT(*) AS COUNT
FROM
    (SELECT
        TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS DATETIME
    FROM ANIMAL_OUTS
    WHERE TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) >= 9
    AND TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) < 20
    ORDER BY
        DATETIME)
GROUP BY
    DATETIME
ORDER BY
    DATETIME ASC;