SELECT
    b.BOOK_ID
    , a.AUTHOR_NAME
    , TO_CHAR(b.PUBLISHED_DATE, 'yyyy-mm-dd') AS PUBLISHED_DATE
FROM BOOK b, AUTHOR a
WHERE 
    b.AUTHOR_ID = a.AUTHOR_ID
AND
    b.CATEGORY = '경제'
ORDER BY
    PUBLISHED_DATE ASC;